services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - gophers-journal-postgres:/var/lib/postgresql/data
volumes:
  gophers-journal-postgres:
